sudo: false
#dist: trusty
env:
  global:
    - GRADLE_USER_HOME=gradle-cache
    # travis encrypt -r org/repo BINTRAY_USER=...
    - secure: "A4TfIRqnUbZ3AfbvQB89U98au6/N5h1oP4xCuP6rOy/U1SlB8KUCPtxbOCbLimEascAjRU0FLC7SIH59dw9+2hL6OCSd+q3QmqU6W4/QCITCxlIA0wzHDwaiDeTPO/7O0Y+FOHr3F1to6Optuj8ySBeEcKYxIqMZSHturQC087asFGnBTDNjDB5IuAvDqvRlcaNH03JrOLnXcjRpH54v5jts1YfH1JGdGdO/SGgTL6jmF19ztFSbmBBoOCWWXa2NsiJs372Z9wmB68lQ2vbaBGsoKXW4FRQdlb+gdkLhBG0Vgqnnd+mzip4DAo7O9tdli2BQpywscScVNT9sdBJ8JbwQG0lWZmos6pc4RugFZ8cLZJgi9CQ1XgM1A2HkmYY2ZjE1Kpxlrq0gzs3uNhQbu+DyjJVy+G39XiK67QlLGjIKQxFz4CCsnriw39h9AyO5GCyKLYJD5Y/YNx6XWYo5p2B5c2I8WyzdqedDBuhJk9RBzk2kkoTX2WR7TkiryErRWXOT27Ksv0dIAxMVZXyBAi+A7eFLz0ytY3bnjaIiDbKg7KxlB/ql5FbNMFghtJkp0J+fE58QJN3ioAlVmkuFzUnYumatLeNTw/1usE3Bm3zajucsb3HuxkEE9PagXi7aezDWC0i78FK4mAx9SiPtmR/h9iNUvEfNFbRqAlKuG5I="
    # travis encrypt -r org/repo BINTRAY_KEY=...
    - secure: "X5tWdw/Y+2lHfd/ETqekcXdsOhuLpao1AeNudtDLmA7hx3cLAI3VvmtSPCloehgeknxEFB0BdHN1NFIsQ187NkzsCFBVNQ5YJfZqpPVBgrOda06eRi82KtIPbVDp2Us1FgtpE+xFEgx4WDUM8Of7OBvVbuDOXU73WlltcEe675lAJIQjNBREyqcPgKXYWMcOX9ypPqlj4eucOICr/mK1J8nhdm9EuxYi4mBxnYfLrZkJE8hhwDKp/a3+azlxLaH/BG8BHaGBZ1QLSQB3LEgNz9JaRcvSJU03ouJB2uuAwZVYb0x50J22lQ5KNnd3w84gto9MThroGkOop/KEI8zBGzCGzIX6vDzE3kHftPkusgpZC+CDGWX79Q0WOipZgulyCs72Yf7ntm0r7blae7pFgh/IBvJP0ECFfwAGXTKiBGMQnCvvq6fkHTJs+ZKlwqqOFszadhixQK++C7HkP/cbBdhpHaj8jCWzlinorOqI6EGXtvyZWJGCI3F94Q3UIGu2fOY8bHVIiwyJv17zYr0zqCUug+fpngS6c7FaAFVWFO+y40aiglGNosnWDC1JJ6uD6x38ngpB7RxX7/XDXl+f9DRjVltYguvl3tf5M6+ZOBCFDkn7ZKe2gKGM+Jr5SnQeDiLKq6UWKXUjjBYt4GEU2PgXpLarv18Cp/Y0c/oaePI="
language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - gradle-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./gradlew assemble

script:
  - ./gradlew check

after_success:
  - 'echo "TRAVIS_TAG: $TRAVIS_TAG" - "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"'
  - '[ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ./gradlew bintrayUpload'

